import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font]
size = 13.0
[font.normal]
family = "JetBrainsMono nerd font"
style = "Regular"

[font.bold]
family = "JetBrainsMono nerd font"
style = "Bold"

[font.italic]
family = "JetBrainsMono nerd font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono nerd font"
style = "Bold Italic"

[window]
opacity = 0.9
padding.x = 10
padding.y = 5

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[selection]
# Characters that are used as separators for "semantic words" in Alacritty
semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"  # Default: ",│`|:\"' ()[]{}<>\\t"
# When set to true, selected text will be copied to the primary clipboard
save_to_clipboard = true  # Default: false
